name: 'GitHub Release from Tag'
author: 'Eloquent'
branding:
  icon: 'tag'
  color: '#6bc46d'
description: 'Publish GitHub releases from tags, supporting Markdown and SemVer'
env:
  GITHUB_TOKEN: 'A GitHub token'
runs:
  using: 'docker'
  image: 'Dockerfile'
