name: Publish SemVer tags
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish SemVer tags
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git user
        uses: fregante/setup-git-user@v1
      - name: Publish SemVer tags
        uses: kellyselden/move-semver-tags-action@v3
        with:
          copy-annotations: true
