name: Publish release
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if tag is SemVer
        id: check-tag
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=is-semver::true
            echo "Tag is SemVer"
          else
            echo "Tag is not SemVer"
          fi
      - name: Publish release
        uses: eloquent/github-release-action@main
        with:
          discussionCategory: ${{ (steps.check-tag.outputs.is-semver == 'true') && 'Releases' }}
